In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\neide\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\neide\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.8 MB 7.2 MB/s eta 0:00:02
   ---------------------------------------- 9.8/9.8 MB 21.2 MB/s  0:00:00
Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl (12.7 MB)
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   -------- ------------------------------- 2.6/12.7 MB 103.6 MB/s eta 0:00:01
   -------- ------------------------------- 2.6/12.7 MB 103.6 MB/s eta 0:00:01
   --------- ------------------------------ 2.9/12.7 MB 5.7 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.7 MB 5.7 MB/s eta 0:00:02
   ------------------- -------------------- 6.3/12.7 MB 5.7 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.7 MB 5.7 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.7 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.7 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 6.8 MB/s  0:00:01
Downloading tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.5.3 pandas-3.0.6 tzdata-2026.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [7]:
clientes = pd.read_excel('clientes.xlsx')

In [10]:
ventas = pd.read_excel('ventastaller.xlsx')

In [11]:
clientes.head()

  id_cliente nombre_cliente     ciudad segmento
0        C01     Ana Torres    Pereira  Premium
1        C02     Luis Gómez  Manizales  Regular
2        C03    María López    Armenia  Premium
3        C04    Carlos Ruiz    Pereira  Regular
4        C05  Sofía Herrera       Cali  Premium

In [12]:
clientes.tail

<bound method NDFrame.tail of   id_cliente nombre_cliente     ciudad segmento
0        C01     Ana Torres    Pereira  Premium
1        C02     Luis Gómez  Manizales  Regular
2        C03    María López    Armenia  Premium
3        C04    Carlos Ruiz    Pereira  Regular
4        C05  Sofía Herrera       Cali  Premium
5        C06    Juan Castro   Medellín  Regular
6        C07  Valentina Gil     Bogotá  Premium
7        C08   Andrés Mejía    Armenia  Regular
8        C09    Laura Rojas    Pereira  Premium
9        C10  Daniel Vargas  Manizales  Regular>

In [13]:
clientes.tail(5
              )

  id_cliente nombre_cliente     ciudad segmento
5        C06    Juan Castro   Medellín  Regular
6        C07  Valentina Gil     Bogotá  Premium
7        C08   Andrés Mejía    Armenia  Regular
8        C09    Laura Rojas    Pereira  Premium
9        C10  Daniel Vargas  Manizales  Regular

In [14]:
clientes.info

<bound method DataFrame.info of   id_cliente nombre_cliente     ciudad segmento
0        C01     Ana Torres    Pereira  Premium
1        C02     Luis Gómez  Manizales  Regular
2        C03    María López    Armenia  Premium
3        C04    Carlos Ruiz    Pereira  Regular
4        C05  Sofía Herrera       Cali  Premium
5        C06    Juan Castro   Medellín  Regular
6        C07  Valentina Gil     Bogotá  Premium
7        C08   Andrés Mejía    Armenia  Regular
8        C09    Laura Rojas    Pereira  Premium
9        C10  Daniel Vargas  Manizales  Regular>

In [15]:
ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_Venta         51 non-null     str
 1   Fecha            51 non-null     datetime64[us]
 2   Cliente          51 non-null     str
 3   Ciudad           51 non-null     str
 4   Producto         51 non-null     str
 5   Categoría        51 non-null     str
 6   Cantidad         49 non-null     float64
 7   Precio_Unitario  51 non-null     int64
 8   Estado           51 non-null     str
dtypes: datetime64[us](1), float64(1), int64(1), str(6)
memory usage: 3.7 KB

In [17]:
ventas.head(10
            )

,ID_Venta,Fecha,Cliente,Ciudad,Producto,Categoría,Cantidad,Precio_Unitario,Estado
0,V001,2026-01-01,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado
1,V002,2026-01-02,Carlos Gómez,pereira,Mouse,tecnologia,5.0,85000,completado
2,V003,2026-01-03,María Díaz,PEREIRA,Teclado,Tecnología,3.0,120000,COMPLETADO
3,V004,2026-01-04,Juan López,Bogotá,Monitor,tecnologia,1.0,850000,Pendiente
4,V005,2026-01-05,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado
5,V006,2026-01-06,Pedro Ruiz,Medellín,Mouse,Tecnología,10.0,85000,Completado
6,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado
7,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado
8,V008,2026-01-08,Sofía Castro,Cali,Teclado,TECNOLOGIA,4.0,120000,Completado
9,V009,2026-01-09,Andrés Rojas,Cali,Monitor,Tecnología,NaN,850000,Pendiente

In [ ]:
ventas.shape
#esto es para mostrar el tamaño del dataframe, es decir, cuantas filas y columnas tiene

(51, 9)

In [ ]:
ventas.columns
#esto es para mostrar el nombre de las columnas del dataframe

Index(['ID_Venta', 'Fecha', 'Cliente', 'Ciudad', 'Producto', 'Categoría',
       'Cantidad', 'Precio_Unitario', 'Estado'],
      dtype='str')

In [ ]:
ventas [['Producto','Precio_Unitario']]
#esto es para mostrar solo las columnas de Producto y Precio_Unitario del dataframe ventas

   Producto  Precio_Unitario
0    Laptop          2500000
1     Mouse            85000
2   Teclado           120000
3   Monitor           850000
4    Laptop          2500000
5     Mouse            85000
6    Laptop          2500000
7    Laptop          2500000
8   Teclado           120000
9   Monitor           850000
10   Laptop          2500000
11    Mouse            85000
12  Teclado           120000
13  Monitor           850000
14   Laptop          2500000
15    Mouse            85000
16  Teclado           120000
17  Monitor           850000
18   Laptop          2500000
19    Mouse            85000
20  Teclado           120000
21  Monitor           850000
22   Laptop          2500000
23    Mouse            85000
24  Monitor           850000
25   Laptop          2500000
26  Teclado           120000
27    Mouse            85000
28  Monitor           850000
29   Laptop          2500000
30    Mouse            85000
31  Teclado           120000
32   Laptop          2500000
33  Monitor           850000
34    Mouse            85000
35   Laptop          2500000
36  Teclado           120000
37  Monitor           850000
38   Laptop          2500000
39    Mouse            85000
40  Teclado           120000
41  Monitor           850000
42   Laptop          2500000
43    Mouse            85000
44  Teclado           120000
45  Monitor           850000
46   Laptop          2500000
47    Mouse            85000
48  Teclado           120000
49  Monitor           850000
50   Laptop          2500000

In [ ]:
ventas [ventas['Precio_Unitario'] > 100000]
#esto es para mostrar solo las filas del dataframe ventas donde el Precio_Unitario es mayor a 100000

,ID_Venta,Fecha,Cliente,Ciudad,Producto,Categoría,Cantidad,Precio_Unitario,Estado
0,V001,2026-01-01,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado
2,V003,2026-01-03,María Díaz,PEREIRA,Teclado,Tecnología,3.0,120000,COMPLETADO
3,V004,2026-01-04,Juan López,Bogotá,Monitor,tecnologia,1.0,850000,Pendiente
4,V005,2026-01-05,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado
6,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado
7,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado
8,V008,2026-01-08,Sofía Castro,Cali,Teclado,TECNOLOGIA,4.0,120000,Completado
9,V009,2026-01-09,Andrés Rojas,Cali,Monitor,Tecnología,NaN,850000,Pendiente
10,V010,2026-01-10,Natalia Díaz,Bogotá,Laptop,Tecnología,1.0,2500000,Completado
12,V012,2026-01-12,Camila Soto,Pereira,Teclado,Tecnología,2.0,120000,completado
13,V013,2026-01-13,Daniel Vargas,Pereira,Monitor,tecnologia,2.0,850000,Completado
14,V014,2026-01-14,Valentina Cruz,PEREIRA,Laptop,Tecnología,1.0,2500000,Pendiente
16,V016,2026-01-16,Laura Torres,bogota,Teclado,TECNOLOGIA,3.0,120000,completado
17,V017,2026-01-17,Pedro Ruiz,Medellín,Monitor,Tecnologia,1.0,850000,Completado
18,V018,2026-01-18,Sofía Castro,Cali,Laptop,Tecnología,2.0,2500000,Completado
20,V020,2026-01-20,Ana Pérez,Pereira,Teclado,tecnologia,5.0,120000,Completado
21,V021,2026-01-21,Carlos Gómez,pereira,Monitor,Tecnología,2.0,850000,Completado
22,V022,2026-01-22,María Díaz,PEREIRA,Laptop,Tecnología,1.0,2500000,COMPLETADO
24,V024,2026-01-24,Laura Torres,bogota,Monitor,Tecnología,1.0,850000,Completado
25,V025,2026-01-25,Pedro Ruiz,Medellín,Laptop,Tecnología,2.0,2500000,Completado
26,V026,2026-01-26,Sofía Castro,Cali,Teclado,TECNOLOGIA,4.0,120000,Completado
28,V028,2026-01-28,Felipe Mora,Medellín,Monitor,Tecnología,2.0,850000,Pendiente
29,V029,2026-01-29,Camila Soto,Pereira,Laptop,tecnologia,1.0,2500000,Completado
31,V031,2026-01-31,Valentina Cruz,PEREIRA,Teclado,TECNOLOGIA,2.0,120000,Completado
32,V032,2026-02-01,Andrés Rojas,Cali,Laptop,Tecnología,1.0,2500000,Pendiente
33,V033,2026-02-02,Ana Pérez,Pereira,Monitor,tecnologia,2.0,850000,Completado
35,V035,2026-02-04,María Díaz,PEREIRA,Laptop,Tecnología,1.0,2500000,COMPLETADO
36,V036,2026-02-05,Juan López,Bogotá,Teclado,tecnologia,3.0,120000,Pendiente
37,V037,2026-02-06,Laura Torres,bogota,Monitor,Tecnología,1.0,850000,Completado
38,V038,2026-02-07,Pedro Ruiz,Medellín,Laptop,Tecnología,2.0,2500000,Completado
40,V040,2026-02-09,Natalia Díaz,Bogotá,Teclado,Tecnologia,2.0,120000,completado
41,V041,2026-02-10,Felipe Mora,Medellín,Monitor,Tecnología,1.0,850000,Pendiente
42,V042,2026-02-11,Camila Soto,Pereira,Laptop,tecnologia,1.0,2500000,Completado
44,V044,2026-02-13,Valentina Cruz,PEREIRA,Teclado,TECNOLOGIA,3.0,120000,Completado
45,V045,2026-02-14,Andrés Rojas,Cali,Monitor,Tecnología,2.0,850000,Pendiente
46,V046,2026-02-15,Ana Pérez,Pereira,Laptop,Tecnología,1.0,2500000,Completado
48,V048,2026-02-17,María Díaz,PEREIRA,Teclado,Tecnología,2.0,120000,COMPLETADO
49,V049,2026-02-18,Juan López,Bogotá,Monitor,tecnologia,1.0,850000,Pendiente
50,V050,2026-02-19,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado

In [29]:
ventas ['Precio_Final'] = ventas['Precio_Unitario'] * 0.19

In [30]:
ventas.head

<bound method NDFrame.head of    ID_Venta      Fecha         Cliente      Ciudad Producto   Categoría  \
0      V001 2026-01-01       Ana Pérez     Pereira   Laptop  Tecnología
1      V002 2026-01-02    Carlos Gómez     pereira    Mouse  tecnologia
2      V003 2026-01-03     María Díaz      PEREIRA  Teclado  Tecnología
3      V004 2026-01-04      Juan López      Bogotá  Monitor  tecnologia
4      V005 2026-01-05    Laura Torres      bogota   Laptop  Tecnología
5      V006 2026-01-06      Pedro Ruiz    Medellín    Mouse  Tecnología
6      V007 2026-01-07       Ana Pérez     Pereira   Laptop  Tecnología
7      V007 2026-01-07       Ana Pérez     Pereira   Laptop  Tecnología
8      V008 2026-01-08    Sofía Castro        Cali  Teclado  TECNOLOGIA
9      V009 2026-01-09    Andrés Rojas        Cali  Monitor  Tecnología
10     V010 2026-01-10    Natalia Díaz      Bogotá   Laptop  Tecnología
11     V011 2026-01-11     Felipe Mora    Medellín    Mouse  Tecnologia
12     V012 2026-01-12     Camila Soto    Pereira   Teclado  Tecnología
13     V013 2026-01-13   Daniel Vargas     Pereira  Monitor  tecnologia
14     V014 2026-01-14  Valentina Cruz     PEREIRA   Laptop  Tecnología
15     V015 2026-01-15    Andrés Rojas        Cali    Mouse  Tecnología
16     V016 2026-01-16    Laura Torres      bogota  Teclado  TECNOLOGIA
17     V017 2026-01-17      Pedro Ruiz    Medellín  Monitor  Tecnologia
18     V018 2026-01-18    Sofía Castro        Cali   Laptop  Tecnología
19     V019 2026-01-19      Juan López      Bogotá    Mouse  Tecnología
20     V020 2026-01-20       Ana Pérez     Pereira  Teclado  tecnologia
21     V021 2026-01-21    Carlos Gómez     pereira  Monitor  Tecnología
22     V022 2026-01-22      María Díaz     PEREIRA   Laptop  Tecnología
23     V023 2026-01-23      Juan López      Bogotá    Mouse  tecnologia
24     V024 2026-01-24    Laura Torres      bogota  Monitor  Tecnología
25     V025 2026-01-25      Pedro Ruiz    Medellín   Laptop  Tecnología
26     V026 2026-01-26    Sofía Castro        Cali  Teclado  TECNOLOGIA
27     V027 2026-01-27    Natalia Díaz      Bogotá    Mouse  Tecnologia
28     V028 2026-01-28     Felipe Mora   Medellín   Monitor  Tecnología
29     V029 2026-01-29     Camila Soto     Pereira   Laptop  tecnologia
30     V030 2026-01-30   Daniel Vargas     Pereira    Mouse  Tecnología
31     V031 2026-01-31  Valentina Cruz     PEREIRA  Teclado  TECNOLOGIA
32     V032 2026-02-01    Andrés Rojas        Cali   Laptop  Tecnología
33     V033 2026-02-02       Ana Pérez     Pereira  Monitor  tecnologia
34     V034 2026-02-03    Carlos Gómez     pereira    Mouse  Tecnología
35     V035 2026-02-04      María Díaz     PEREIRA   Laptop  Tecnología
36     V036 2026-02-05      Juan López      Bogotá  Teclado  tecnologia
37     V037 2026-02-06    Laura Torres      bogota  Monitor  Tecnología
38     V038 2026-02-07      Pedro Ruiz    Medellín   Laptop  Tecnología
39     V039 2026-02-08    Sofía Castro        Cali    Mouse  TECNOLOGIA
40     V040 2026-02-09    Natalia Díaz      Bogotá  Teclado  Tecnologia
41     V041 2026-02-10     Felipe Mora    Medellín  Monitor  Tecnología
42     V042 2026-02-11     Camila Soto    Pereira    Laptop  tecnologia
43     V043 2026-02-12   Daniel Vargas     Pereira    Mouse  Tecnología
44     V044 2026-02-13  Valentina Cruz     PEREIRA  Teclado  TECNOLOGIA
45     V045 2026-02-14    Andrés Rojas        Cali  Monitor  Tecnología
46     V046 2026-02-15       Ana Pérez     Pereira   Laptop  Tecnología
47     V047 2026-02-16    Carlos Gómez     pereira    Mouse  tecnologia
48     V048 2026-02-17      María Díaz     PEREIRA  Teclado  Tecnología
49     V049 2026-02-18      Juan López      Bogotá  Monitor  tecnologia
50     V050 2026-02-19    Laura Torres      bogota   Laptop  Tecnología

    Cantidad  Precio_Unitario      Estado  Precio_Final
0        2.0          2500000  Completado      475000.0
1        5.0            85000  completado       16150.0
2        3.0           120000  COMPLETADO       22800.0
3        1.0           850000   Pendiente      161500.0
4        1.0          2500000  Completado      475000.0
5       10.0            85000  Completado       16150.0
6        2.0          2500000  Completado      475000.0
7        2.0          2500000  Completado      475000.0
8        4.0           120000  Completado       22800.0
9        NaN           850000   Pendiente      161500.0
10       1.0          2500000  Completado      475000.0
11       NaN            85000  Completado       16150.0
12       2.0           120000  completado       22800.0
13       2.0           850000  Completado      161500.0
14       1.0          2500000   Pendiente      475000.0
15       8.0            85000  Completado       16150.0
16       3.0           120000  completado       22800.0
17       1.0           850000  Completado      161500.0
18       2.0          2500000  Completado      475000.0
19       4.0            85000   Pendiente       16150.0
20       5.0           120000  Completado       22800.0
21       2.0           850000  Completado      161500.0
22       1.0          2500000  COMPLETADO      475000.0
23       6.0            85000   Pendiente       16150.0
24       1.0           850000  Completado      161500.0
25       2.0          2500000  Completado      475000.0
26       4.0           120000  Completado       22800.0
27       7.0            85000  completado       16150.0
28       2.0           850000   Pendiente      161500.0
29       1.0          2500000  Completado      475000.0
30      10.0            85000  Completado       16150.0
31       2.0           120000  Completado       22800.0
32       1.0          2500000   Pendiente      475000.0
33       2.0           850000  Completado      161500.0
34       5.0            85000  Completado       16150.0
35       1.0          2500000  COMPLETADO      475000.0
36       3.0           120000   Pendiente       22800.0
37       1.0           850000  Completado      161500.0
38       2.0          2500000  Completado      475000.0
39       9.0            85000  Completado       16150.0
40       2.0           120000  completado       22800.0
41       1.0           850000   Pendiente      161500.0
42       1.0          2500000  Completado      475000.0
43       4.0            85000  Completado       16150.0
44       3.0           120000  Completado       22800.0
45       2.0           850000   Pendiente      161500.0
46       1.0          2500000  Completado      475000.0
47       6.0            85000  Completado       16150.0
48       2.0           120000  COMPLETADO       22800.0
49       1.0           850000   Pendiente      161500.0
50       1.0          2500000  Completado      475000.0  >

In [31]:
ventas.head(5
            )

,ID_Venta,Fecha,Cliente,Ciudad,Producto,Categoría,Cantidad,Precio_Unitario,Estado,Precio_Final
0,V001,2026-01-01,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0
1,V002,2026-01-02,Carlos Gómez,pereira,Mouse,tecnologia,5.0,85000,completado,16150.0
2,V003,2026-01-03,María Díaz,PEREIRA,Teclado,Tecnología,3.0,120000,COMPLETADO,22800.0
3,V004,2026-01-04,Juan López,Bogotá,Monitor,tecnologia,1.0,850000,Pendiente,161500.0
4,V005,2026-01-05,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado,475000.0

In [38]:
ventas [ventas['Producto'] == 'Laptop']

,ID_Venta,Fecha,Cliente,Ciudad,Producto,Categoría,Cantidad,Precio_Unitario,Estado,Precio_Final
0,V001,2026-01-01,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0
4,V005,2026-01-05,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado,475000.0
6,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0
7,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0
10,V010,2026-01-10,Natalia Díaz,Bogotá,Laptop,Tecnología,1.0,2500000,Completado,475000.0
14,V014,2026-01-14,Valentina Cruz,PEREIRA,Laptop,Tecnología,1.0,2500000,Pendiente,475000.0
18,V018,2026-01-18,Sofía Castro,Cali,Laptop,Tecnología,2.0,2500000,Completado,475000.0
22,V022,2026-01-22,María Díaz,PEREIRA,Laptop,Tecnología,1.0,2500000,COMPLETADO,475000.0
25,V025,2026-01-25,Pedro Ruiz,Medellín,Laptop,Tecnología,2.0,2500000,Completado,475000.0
29,V029,2026-01-29,Camila Soto,Pereira,Laptop,tecnologia,1.0,2500000,Completado,475000.0
32,V032,2026-02-01,Andrés Rojas,Cali,Laptop,Tecnología,1.0,2500000,Pendiente,475000.0
35,V035,2026-02-04,María Díaz,PEREIRA,Laptop,Tecnología,1.0,2500000,COMPLETADO,475000.0
38,V038,2026-02-07,Pedro Ruiz,Medellín,Laptop,Tecnología,2.0,2500000,Completado,475000.0
42,V042,2026-02-11,Camila Soto,Pereira,Laptop,tecnologia,1.0,2500000,Completado,475000.0
46,V046,2026-02-15,Ana Pérez,Pereira,Laptop,Tecnología,1.0,2500000,Completado,475000.0
50,V050,2026-02-19,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado,475000.0